// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9zTiKg6SyOuR9VpBRWWmEbCZHUQxuRM',
    appId: '1:712175023328:web:bce83b63ab6a26dc3dcc85',
    messagingSenderId: '712175023328',
    projectId: 'cinetrack-e679e',
    authDomain: 'cinetrack-e679e.firebaseapp.com',
    storageBucket: 'cinetrack-e679e.firebasestorage.app',
    measurementId: 'G-H4J4DEQXZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nM1lwBOHE95hTcn3EjcvCczE0l5t0Os',
    appId: '1:712175023328:android:4e46786fdf89212c3dcc85',
    messagingSenderId: '712175023328',
    projectId: 'cinetrack-e679e',
    storageBucket: 'cinetrack-e679e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_MrXxVk-TAMQU7WISdLv3CrDIu5ei84',
    appId: '1:712175023328:ios:d95fb4101f49a75d3dcc85',
    messagingSenderId: '712175023328',
    projectId: 'cinetrack-e679e',
    storageBucket: 'cinetrack-e679e.firebasestorage.app',
    iosBundleId: 'com.example.cineTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_MrXxVk-TAMQU7WISdLv3CrDIu5ei84',
    appId: '1:712175023328:ios:d95fb4101f49a75d3dcc85',
    messagingSenderId: '712175023328',
    projectId: 'cinetrack-e679e',
    storageBucket: 'cinetrack-e679e.firebasestorage.app',
    iosBundleId: 'com.example.cineTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM9zTiKg6SyOuR9VpBRWWmEbCZHUQxuRM',
    appId: '1:712175023328:web:ddee49d8a03b21e73dcc85',
    messagingSenderId: '712175023328',
    projectId: 'cinetrack-e679e',
    authDomain: 'cinetrack-e679e.firebaseapp.com',
    storageBucket: 'cinetrack-e679e.firebasestorage.app',
    measurementId: 'G-NS5BPL1VL6',
  );
}
